version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      go:
        patterns: ['*']

  - package-ecosystem: pip
    directory: /e2e/sdk
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      e2e-python:
        patterns: ['*']

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns: ['*']
